- name:  redis repo installation
  ansible.builtin.yum:
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: installed
    disable_gpg_check: true


- name: enable redis 6.2
  ansible.builtin.shell: yum module enable redis:remi-6.2 -y

- name: Install redis 6.2
  ansible.builtin.dnf:
    name: redis
    state: installed


- name: Update redis Listen Address-/etc/redis.conf
  ansible.builtin.replace:
    path: /etc/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'
- name: Update redis Listen Address-/etc/redis/redis.conf
  ansible.builtin.replace:
    path: /etc/redis/redis.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start {{ component}}
  ansible.builtin.systemd:
    name: "{{ component}}"
    state: restarted
    enabled: yes


echo -e "${color} enable module${nocolor}"
yum module enable redis:remi-6.2 -y
status_check $?


echo -e "${color} install redis${nocolor}"
yum install redis -y
status_check $?


echo -e "${color}  conf file${nocolor}"
sed -i -e 's?127.0.0.1?0.0.0.0?' /etc/redis.conf /etc/redis/redis.conf
status_check $?


echo -e "${color} service restart${nocolor}"
systemctl enable redis
systemctl start redis
status_check $?