- name:  Install MySQL Client
  ansible.builtin.yum:
    name: mysql
    state: installed

- name:  Load schema
  ansible.builtin.shell: mysql -h mysql-dev.manibabu.site -uroot -pRoboShop@1 </app/schema/{{ component }}.sql

