- name: Execute the command in remote shell; stdout goes to the specified file on the remote
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name:  Installing Nginx Server
  ansible.builtin.yum:
    name: nodejs
    state: present








    app_presetup
    
    echo -e "${color} Install NodeJS Dependencies${nocolor}"
    npm install  &>>$log_file
    stat_check $?
    
    systemd_setup
}
