- name: Execute the command in remote shell; stdout goes to the specified file on the remote
  ansible.builtin.shell: curl -sL https://rpm.nodesource.com/setup_lts.x | bash

- name:  Installing Nginx Server
  ansible.builtin.yum:
    name: nodejs
    state: present

- name: app presetup
  ansible.builtin.import_tasks:
    file: app_presetup.yml

- name: Load nodejs dependencies

  ansible.builtin.shell: npm install
  args:
    chdir: /app

- name: systemd restart
  ansible.builtin.import_tasks:
    file: systemd_setup.yml

- name: mongo_schema_setup
  ansible.builtin.import_tasks:
    file: mongo_schema_setup
    when mongo_schema

